# Generated by Django 5.1.3 on 2024-11-27 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 27, 17, 2, 3, 522354, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
