# Generated by Django 5.1.3 on 2024-11-17 11:43

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 24, 11, 43, 52, 895719, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='auction',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
