# Generated by Django 5.1.3 on 2024-11-17 14:28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_end_time_auction_start_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='action_type',
        ),
        migrations.AddField(
            model_name='auction',
            name='auction_type',
            field=models.CharField(choices=[('single', 'Single Product Auction'), ('multiple', 'Multiple Products Auction')], default='single', max_length=8),
        ),
        migrations.AddField(
            model_name='auction',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='auctions', to='auctions.product'),
        ),
        migrations.AddField(
            model_name='auction',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_auctions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auction',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_auctions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 24, 14, 28, 28, 99634, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='auction',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.product'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(default='planned', max_length=20),
        ),
    ]
