# Generated by Django 5.1.3 on 2024-11-17 14:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_auction_action_type_auction_auction_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='starting_price',
        ),
        migrations.AddField(
            model_name='bid',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids_product', to='auctions.product'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 24, 14, 52, 28, 509764, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids_auction', to='auctions.auction'),
        ),
    ]
