# Generated by Django 5.1.3 on 2024-11-27 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auction_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 27, 17, 50, 37, 445553, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
