# Generated by Django 5.1.3 on 2024-11-17 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_product_end_at_remove_product_starting_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='starting_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='auction_type',
            field=models.CharField(choices=[('single', 'Single Product Auction'), ('multiple', 'Multiple Products Auction')], default='single', max_length=20),
        ),
        migrations.AlterField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 24, 15, 43, 52, 892840, tzinfo=datetime.timezone.utc)),
        ),
    ]
