# Generated by Django 5.1.3 on 2024-12-01 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bid_status_alter_auction_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 1, 11, 9, 54, 862801, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
