# Generated by Django 5.1.3 on 2024-11-18 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rating_rated_user_alter_auction_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 25, 17, 16, 37, 326896, tzinfo=datetime.timezone.utc)),
        ),
    ]
