# Generated by Django 5.1.3 on 2024-12-01 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_auction_end_time_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 1, 16, 12, 44, 810520, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
