# Generated by Django 5.1.3 on 2024-12-01 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_auction_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 1, 17, 39, 30, 472507, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('user', 'User'), ('seller', 'Seller'), ('manager', 'Manager'), ('blocked', 'Blocked')], default='user', max_length=10),
        ),
    ]
