# Generated by Django 5.1.3 on 2024-12-08 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_chat_sender_name_alter_auction_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 8, 15, 48, 44, 640004, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
